
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Airbnb_data_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'Airbnb_data_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  Airbnb_data_project:
    # this is defult conf for all the project
    +materialized: view
    +post-hook:
      - "Grant select on {{this}} to role reporter"

    # config for each model
    src:
      +materialized: ephemeral 
      +schema: dev
    
    dim:
      +materialized: table
      +schema: dev
    
    fct:
      +materialized: incremental
      +schema: dev
    
    mart:
      +materialized: table
      +schema: dev

seeds:
  Airbnb_data_project:      # your project name
    +schema: dev         # all seeds will go into dev schema
