-- Use an admin role
USE ROLE ACCOUNTADMIN;

-- Create the `transform` role
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Create the `dbt` user and assign to role
CREATE USER IF NOT EXISTS dbt
  PASSWORD='dbtPassword123'
  LOGIN_NAME='dbt'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_NAMESPACE='AIRBNB.RAW'
  COMMENT='DBT user used for data transformation';
ALTER USER dbt SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM to USER dbt;

-- Create our database and schemas
CREATE DATABASE IF NOT EXISTS AIRBNB;
CREATE SCHEMA IF NOT EXISTS AIRBNB.RAW;

-- Set up permissions to role `transform`
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM; 
GRANT ALL ON DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA AIRBNB.RAW to ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA AIRBNB.RAW to ROLE TRANSFORM;



------------------------------------------------------------------------------------------------------
create role if not exists reporter;
CREATE USER IF NOT EXISTS preset 
    PASSWORD='presetPassword123' 
    LOGIN_NAME='preset' 
    MUST_CHANGE_PASSWORD=FALSE 
    DEFAULT_WAREHOUSE='COMPUTE_WH' 
    DEFAULT_ROLE='REPORTER' 
    DEFAULT_NAMESPACE='AIRBNB.DEV' 
    COMMENT='Preset user for creating reports';

GRANT ROLE REPORTER TO USER PRESET; 
GRANT ROLE REPORTER TO ROLE ACCOUNTADMIN; 
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE REPORTER; 
GRANT USAGE ON DATABASE AIRBNB TO ROLE REPORTER; 
GRANT USAGE ON SCHEMA AIRBNB.RAW_DEV TO ROLE REPORTER;
