version: 2

models:
  #------------------------------------------------------------------ tests related to dim_listings_cleansed ----------------------------------------------------------#
  - name: dim_listings_cleansed
    description: "Cleansed listings data"
    columns:
      - name: listing_id
        description: "Unique identifier for each listing"
        tests:
          - unique
          - not_null

      - name: host_id
        description: "Unique identifier for each host"
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: "Type of room being listed ex: Entire home/apt, Private room, Shared room, Hotel room"
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value:
              column_name: minimum_nights

  # --------------------------------------------------------------- tests related to dim_hosts_cleansed ---------------------------------------------------------------#
  - name: dim_hosts_cleansed
    description: "Cleansed hosts data"
    columns:
      - name: host_id
        description: "Unique identifier for each host"
        tests:
          - unique
          - not_null

      - name: host_name
        description: "Name of the host"
        tests:
          - not_null

      - name: is_superhost
        description: "Indicates whether the host is a superhost"
        tests:
          - accepted_values:
              values: ['t', 'f']

  # --------------------------------------------------------------- tests related to fct_reviews --------------------------------------------------------------#
  - name: fct_reviews
    description: "Fact table for reviews"
    columns:
      - name: listing_id
        description: "Unique identifier for each listing"
        tests:
          - not_null
          - relationships:
              to: ref('dim_listings_cleansed')
              field: listing_id

      - name: reviewer_name
        description: "Name of the reviewer"
        tests:
          - not_null

      - name: review_sentiment
        description: "Text of the review"
        tests:
          - accepted_values:
              values: ['positive', 'neutral', 'negative']

  # --------------------------------------------------------------- tests related to dim_listings_w_hosts --------------------------------------------------------------#
  - name: dim_listings_w_hosts
    description: "Date when the review was written"
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb_raw_data', 'RAW_LISTINGS')
    columns:
      - name: price
        description: "Price of the listing"
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500

          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1000
              max_value: 9000
              config:
                severity: warn