version: 2.0

sources:
  - name: airbnb_raw_data
    database: AIRBNB
    schema: RAW
    tables: 
        - name: RAW_HOSTS
          description: "Raw hosts data"
        - name: RAW_LISTINGS
          description: "Raw listings data"
        - name: RAW_REVIEWS
          description: "Raw reviews data"