version: 2.0

sources:
  - name: airbnb_raw_data
    database: AIRBNB
    schema: RAW
    tables: 
        - name: RAW_HOSTS
          description: "Raw hosts data"
        - name: RAW_LISTINGS
          description: "Raw listings data"
          columns:
            - name: room_type
              tests:
                - dbt_expectations.expect_column_distinct_count_to_equal:
                    value: 4
            - name: price
              tests:
                - dbt_expectations.expect_column_values_to_match_regex:
                    regex: "^\\\\$[0-9][0-9\\\\.]+$"
        - name: RAW_REVIEWS
          description: "Raw reviews data"